import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f1b950",
    width: "100%",
  },
  image: {
    width: 80,
    height: 80,
    marginTop: 10,
  },
  text: {
    fontSize: 20,
    fontWeight: "bold",
    width: "90%",
    marginTop: 15,
    marginBottom: 5,
    textAlign: "left",
  },
  mainInputs: {
    width: "90%",
    height: 45,
    backgroundColor: "#181719",
    fontSize: 20,
    fontStyle: "italic",
    paddingHorizontal: 15,
    borderRadius: 10,
    color: "#f1b950",
  },
  button: {
    width: "90%",
    height: 45,
    backgroundColor: "#44496f",
    marginTop: 10,
    borderRadius: 10,
    textAlign: "center",
    textAlignVertical: "center",
    fontSize: 20,
    fontWeight: "bold",
    color: "#f1b950",
  },
  sendButton: {
    width: "90%",
    height: 45,
    backgroundColor: "#c22a2a",
    marginTop: 40,
    borderRadius: 10,
    textAlign: "center",
    textAlignVertical: "center",
    fontSize: 20,
    fontWeight: "bold",
    color: "#f1b950",
  },
  description: {
    width: "90%",
    height: 90,
    backgroundColor: "#181719",
    fontSize: 20,
    textAlignVertical: "top",
    fontStyle: "italic",
    paddingHorizontal: 15,
    borderRadius: 10,
    color: "#f1b950",
  },
  homeButton: {
    width: 30,
    height: 30,
    marginTop: 25,
  },
});
